Repository milieuinfo/webcomponent-vl-ui-checkbox, pull requests merged in 2019-09, with the labels that each got.

#19 UIG-218
  vl-checkbox.src.js
Labels: maintenance

#20 Update link naar demo
  vl-checkbox.src.js
Labels: maintenance

#22 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#27 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#31 Bamboo permissions configureren via permissions.yml
  bamboo-specs/bamboo.yml
  bamboo-specs/permissions.yml
  package-lock.json
  package.json
Labels: chore

#33 Automatic commit via update script
  bamboo-specs/bamboo.yml
  bamboo-specs/out.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
  style.css.map
Labels: maintenance

#34 Update util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  bamboo-specs/out.yml
  bamboo-specs/permissions.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
Labels: chore

#35 Update util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: maintenance

#36 Update package-lock
  package-lock.json
Labels: maintenance

#8 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#40 Update vl-ui-util
  CODEOWNERS
  package-lock.json
  package.json
Labels: maintenance
